- name: My first play
  hosts: all
  tasks:

  - name: update repo index
    apt:
     update_cache: yes
    when: ansible_distribution == "Debian"
 
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "Debian"
  
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Debian"

  - name: update repo index
    yum:
     update_cache: yes
    when: ansible_distribution == "Rocky"
 
  - name: add php support for apache
    yum:
      name: php
    when: ansible_distribution == "Rocky"
  
  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"
