- name: My first play
  hosts: all
  tasks:

  - name: update repo index
    apt:
     update_cache: yes

  - name: add wget to server
    apt:
      name: wget
      state: latest

  - name: add gpg to server
    apt:
      name: gpg
      state: latest



