- name: My first play
  hosts: all
  tasks:

  - name: update repo index
    apt:
     update_cache: yes

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
