- name: Site Automation
  hosts: all
  pre_tasks:

  - name: update repo index (Debian)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install updates (Rocky)
    tags: always
    yum:
      update_cache: yes
    when: ansible_distribution == "Rocky"

- hosts: all
  roles: 
    - base

- hosts: app_servers
  roles:
    - app_servers

- hosts: db_server
  roles:
    - db_server

- hosts: proxy_server
  roles:
    - proxy_server

- hosts: proxy_container
  roles:
    - proxy_container

