- name: add php support for apache
  tags: apache,apache2,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
